name: push docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Custom docker image tag if needed'
        default: ''

jobs:
  build_and_push:
    name: build_and_push (${{ matrix.docker.repo }})
    strategy:
      matrix:
        docker:
          - repo: planetariumhq/libplanet-remote-kv
            dockerfile: Dockerfile
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v8,linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64,linux/amd64
          tags: ${{ matrix.docker.repo }}:git-${{ github.sha }}
          file: ${{ matrix.docker.dockerfile }}
          build-args: COMMIT=git-${{ github.sha }}
        env:
          BUILDKIT_PROGRESS: 'plain'

  tag:
    name: tag (${{ matrix.docker.repo }})
    strategy:
      matrix:
        docker:
          - repo: planetariumhq/libplanet-remote-kv
    if: github.ref_type == 'tag' || github.event.inputs.imageTag != ''
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: push git tagged version
        run: |
          if [[ -z "${{ github.event.inputs.imageTag }}" ]]; then
            export IMAGE_TAG=${{ github.ref_name }}
          else
            export IMAGE_TAG=${{ github.event.inputs.imageTag }}
          fi

          docker buildx imagetools create \
            --progress=plain \
            --tag ${{ matrix.docker.repo }}:$IMAGE_TAG \
            ${{ matrix.docker.repo }}:git-${{ github.sha }}